
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Agence: 'Agence',
  AgencyEmployee: 'AgencyEmployee',
  Locataire: 'Locataire',
  Quittance: 'Quittance',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AgenceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  adresse: 'adresse',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AgenceScalarFieldEnum = (typeof AgenceScalarFieldEnum)[keyof typeof AgenceScalarFieldEnum]


export const AgencyEmployeeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  agencyId: 'agencyId',
  position: 'position',
  department: 'department',
  hireDate: 'hireDate',
  salary: 'salary',
  isManager: 'isManager',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AgencyEmployeeScalarFieldEnum = (typeof AgencyEmployeeScalarFieldEnum)[keyof typeof AgencyEmployeeScalarFieldEnum]


export const LocataireScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  email: 'email',
  adresse: 'adresse',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LocataireScalarFieldEnum = (typeof LocataireScalarFieldEnum)[keyof typeof LocataireScalarFieldEnum]


export const QuittanceScalarFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  agencyId: 'agencyId',
  amount: 'amount',
  period: 'period',
  paymentDate: 'paymentDate',
  paid: 'paid',
  adresse: 'adresse',
  link: 'link',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type QuittanceScalarFieldEnum = (typeof QuittanceScalarFieldEnum)[keyof typeof QuittanceScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  password: 'password',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const AgenceOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  adresse: 'adresse',
  role: 'role'
} as const

export type AgenceOrderByRelevanceFieldEnum = (typeof AgenceOrderByRelevanceFieldEnum)[keyof typeof AgenceOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const AgencyEmployeeOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  agencyId: 'agencyId',
  position: 'position',
  department: 'department'
} as const

export type AgencyEmployeeOrderByRelevanceFieldEnum = (typeof AgencyEmployeeOrderByRelevanceFieldEnum)[keyof typeof AgencyEmployeeOrderByRelevanceFieldEnum]


export const LocataireOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  email: 'email',
  adresse: 'adresse',
  role: 'role'
} as const

export type LocataireOrderByRelevanceFieldEnum = (typeof LocataireOrderByRelevanceFieldEnum)[keyof typeof LocataireOrderByRelevanceFieldEnum]


export const QuittanceOrderByRelevanceFieldEnum = {
  id: 'id',
  tenantId: 'tenantId',
  agencyId: 'agencyId',
  period: 'period',
  adresse: 'adresse',
  link: 'link'
} as const

export type QuittanceOrderByRelevanceFieldEnum = (typeof QuittanceOrderByRelevanceFieldEnum)[keyof typeof QuittanceOrderByRelevanceFieldEnum]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  password: 'password'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]

