
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Agence` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Agence
 * 
 */
export type AgenceModel = runtime.Types.Result.DefaultSelection<Prisma.$AgencePayload>

export type AggregateAgence = {
  _count: AgenceCountAggregateOutputType | null
  _min: AgenceMinAggregateOutputType | null
  _max: AgenceMaxAggregateOutputType | null
}

export type AgenceMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  adresse: string | null
  role: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgenceMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  adresse: string | null
  role: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgenceCountAggregateOutputType = {
  id: number
  name: number
  email: number
  adresse: number
  role: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AgenceMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  adresse?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type AgenceMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  adresse?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type AgenceCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  adresse?: true
  role?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AgenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agence to aggregate.
   */
  where?: Prisma.AgenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agences to fetch.
   */
  orderBy?: Prisma.AgenceOrderByWithRelationInput | Prisma.AgenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Agences
  **/
  _count?: true | AgenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgenceMaxAggregateInputType
}

export type GetAgenceAggregateType<T extends AgenceAggregateArgs> = {
      [P in keyof T & keyof AggregateAgence]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgence[P]>
    : Prisma.GetScalarType<T[P], AggregateAgence[P]>
}




export type AgenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgenceWhereInput
  orderBy?: Prisma.AgenceOrderByWithAggregationInput | Prisma.AgenceOrderByWithAggregationInput[]
  by: Prisma.AgenceScalarFieldEnum[] | Prisma.AgenceScalarFieldEnum
  having?: Prisma.AgenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgenceCountAggregateInputType | true
  _min?: AgenceMinAggregateInputType
  _max?: AgenceMaxAggregateInputType
}

export type AgenceGroupByOutputType = {
  id: string
  name: string
  email: string
  adresse: string
  role: string
  createdAt: Date
  updatedAt: Date
  _count: AgenceCountAggregateOutputType | null
  _min: AgenceMinAggregateOutputType | null
  _max: AgenceMaxAggregateOutputType | null
}

type GetAgenceGroupByPayload<T extends AgenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgenceGroupByOutputType[P]>
      }
    >
  >



export type AgenceWhereInput = {
  AND?: Prisma.AgenceWhereInput | Prisma.AgenceWhereInput[]
  OR?: Prisma.AgenceWhereInput[]
  NOT?: Prisma.AgenceWhereInput | Prisma.AgenceWhereInput[]
  id?: Prisma.StringFilter<"Agence"> | string
  name?: Prisma.StringFilter<"Agence"> | string
  email?: Prisma.StringFilter<"Agence"> | string
  adresse?: Prisma.StringFilter<"Agence"> | string
  role?: Prisma.StringFilter<"Agence"> | string
  createdAt?: Prisma.DateTimeFilter<"Agence"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agence"> | Date | string
  quittances?: Prisma.QuittanceListRelationFilter
  locataires?: Prisma.LocataireListRelationFilter
  agencyEmployees?: Prisma.AgencyEmployeeListRelationFilter
}

export type AgenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  quittances?: Prisma.QuittanceOrderByRelationAggregateInput
  locataires?: Prisma.LocataireOrderByRelationAggregateInput
  agencyEmployees?: Prisma.AgencyEmployeeOrderByRelationAggregateInput
  _relevance?: Prisma.AgenceOrderByRelevanceInput
}

export type AgenceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.AgenceWhereInput | Prisma.AgenceWhereInput[]
  OR?: Prisma.AgenceWhereInput[]
  NOT?: Prisma.AgenceWhereInput | Prisma.AgenceWhereInput[]
  name?: Prisma.StringFilter<"Agence"> | string
  adresse?: Prisma.StringFilter<"Agence"> | string
  role?: Prisma.StringFilter<"Agence"> | string
  createdAt?: Prisma.DateTimeFilter<"Agence"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agence"> | Date | string
  quittances?: Prisma.QuittanceListRelationFilter
  locataires?: Prisma.LocataireListRelationFilter
  agencyEmployees?: Prisma.AgencyEmployeeListRelationFilter
}, "id" | "email">

export type AgenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AgenceCountOrderByAggregateInput
  _max?: Prisma.AgenceMaxOrderByAggregateInput
  _min?: Prisma.AgenceMinOrderByAggregateInput
}

export type AgenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgenceScalarWhereWithAggregatesInput | Prisma.AgenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgenceScalarWhereWithAggregatesInput | Prisma.AgenceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Agence"> | string
  name?: Prisma.StringWithAggregatesFilter<"Agence"> | string
  email?: Prisma.StringWithAggregatesFilter<"Agence"> | string
  adresse?: Prisma.StringWithAggregatesFilter<"Agence"> | string
  role?: Prisma.StringWithAggregatesFilter<"Agence"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Agence"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Agence"> | Date | string
}

export type AgenceCreateInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceCreateNestedManyWithoutAgenceInput
  locataires?: Prisma.LocataireCreateNestedManyWithoutAgenceInput
  agencyEmployees?: Prisma.AgencyEmployeeCreateNestedManyWithoutAgencyInput
}

export type AgenceUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceUncheckedCreateNestedManyWithoutAgenceInput
  locataires?: Prisma.LocataireUncheckedCreateNestedManyWithoutAgenceInput
  agencyEmployees?: Prisma.AgencyEmployeeUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgenceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUpdateManyWithoutAgenceNestedInput
  locataires?: Prisma.LocataireUpdateManyWithoutAgenceNestedInput
  agencyEmployees?: Prisma.AgencyEmployeeUpdateManyWithoutAgencyNestedInput
}

export type AgenceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUncheckedUpdateManyWithoutAgenceNestedInput
  locataires?: Prisma.LocataireUncheckedUpdateManyWithoutAgenceNestedInput
  agencyEmployees?: Prisma.AgencyEmployeeUncheckedUpdateManyWithoutAgencyNestedInput
}

export type AgenceCreateManyInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgenceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgenceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgenceOrderByRelevanceInput = {
  fields: Prisma.AgenceOrderByRelevanceFieldEnum | Prisma.AgenceOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AgenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgenceScalarRelationFilter = {
  is?: Prisma.AgenceWhereInput
  isNot?: Prisma.AgenceWhereInput
}

export type AgenceNullableScalarRelationFilter = {
  is?: Prisma.AgenceWhereInput | null
  isNot?: Prisma.AgenceWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type AgenceCreateNestedOneWithoutAgencyEmployeesInput = {
  create?: Prisma.XOR<Prisma.AgenceCreateWithoutAgencyEmployeesInput, Prisma.AgenceUncheckedCreateWithoutAgencyEmployeesInput>
  connectOrCreate?: Prisma.AgenceCreateOrConnectWithoutAgencyEmployeesInput
  connect?: Prisma.AgenceWhereUniqueInput
}

export type AgenceUpdateOneRequiredWithoutAgencyEmployeesNestedInput = {
  create?: Prisma.XOR<Prisma.AgenceCreateWithoutAgencyEmployeesInput, Prisma.AgenceUncheckedCreateWithoutAgencyEmployeesInput>
  connectOrCreate?: Prisma.AgenceCreateOrConnectWithoutAgencyEmployeesInput
  upsert?: Prisma.AgenceUpsertWithoutAgencyEmployeesInput
  connect?: Prisma.AgenceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgenceUpdateToOneWithWhereWithoutAgencyEmployeesInput, Prisma.AgenceUpdateWithoutAgencyEmployeesInput>, Prisma.AgenceUncheckedUpdateWithoutAgencyEmployeesInput>
}

export type AgenceCreateNestedOneWithoutLocatairesInput = {
  create?: Prisma.XOR<Prisma.AgenceCreateWithoutLocatairesInput, Prisma.AgenceUncheckedCreateWithoutLocatairesInput>
  connectOrCreate?: Prisma.AgenceCreateOrConnectWithoutLocatairesInput
  connect?: Prisma.AgenceWhereUniqueInput
}

export type AgenceUpdateOneWithoutLocatairesNestedInput = {
  create?: Prisma.XOR<Prisma.AgenceCreateWithoutLocatairesInput, Prisma.AgenceUncheckedCreateWithoutLocatairesInput>
  connectOrCreate?: Prisma.AgenceCreateOrConnectWithoutLocatairesInput
  upsert?: Prisma.AgenceUpsertWithoutLocatairesInput
  disconnect?: Prisma.AgenceWhereInput | boolean
  delete?: Prisma.AgenceWhereInput | boolean
  connect?: Prisma.AgenceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgenceUpdateToOneWithWhereWithoutLocatairesInput, Prisma.AgenceUpdateWithoutLocatairesInput>, Prisma.AgenceUncheckedUpdateWithoutLocatairesInput>
}

export type AgenceCreateNestedOneWithoutQuittancesInput = {
  create?: Prisma.XOR<Prisma.AgenceCreateWithoutQuittancesInput, Prisma.AgenceUncheckedCreateWithoutQuittancesInput>
  connectOrCreate?: Prisma.AgenceCreateOrConnectWithoutQuittancesInput
  connect?: Prisma.AgenceWhereUniqueInput
}

export type AgenceUpdateOneRequiredWithoutQuittancesNestedInput = {
  create?: Prisma.XOR<Prisma.AgenceCreateWithoutQuittancesInput, Prisma.AgenceUncheckedCreateWithoutQuittancesInput>
  connectOrCreate?: Prisma.AgenceCreateOrConnectWithoutQuittancesInput
  upsert?: Prisma.AgenceUpsertWithoutQuittancesInput
  connect?: Prisma.AgenceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgenceUpdateToOneWithWhereWithoutQuittancesInput, Prisma.AgenceUpdateWithoutQuittancesInput>, Prisma.AgenceUncheckedUpdateWithoutQuittancesInput>
}

export type AgenceCreateWithoutAgencyEmployeesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceCreateNestedManyWithoutAgenceInput
  locataires?: Prisma.LocataireCreateNestedManyWithoutAgenceInput
}

export type AgenceUncheckedCreateWithoutAgencyEmployeesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceUncheckedCreateNestedManyWithoutAgenceInput
  locataires?: Prisma.LocataireUncheckedCreateNestedManyWithoutAgenceInput
}

export type AgenceCreateOrConnectWithoutAgencyEmployeesInput = {
  where: Prisma.AgenceWhereUniqueInput
  create: Prisma.XOR<Prisma.AgenceCreateWithoutAgencyEmployeesInput, Prisma.AgenceUncheckedCreateWithoutAgencyEmployeesInput>
}

export type AgenceUpsertWithoutAgencyEmployeesInput = {
  update: Prisma.XOR<Prisma.AgenceUpdateWithoutAgencyEmployeesInput, Prisma.AgenceUncheckedUpdateWithoutAgencyEmployeesInput>
  create: Prisma.XOR<Prisma.AgenceCreateWithoutAgencyEmployeesInput, Prisma.AgenceUncheckedCreateWithoutAgencyEmployeesInput>
  where?: Prisma.AgenceWhereInput
}

export type AgenceUpdateToOneWithWhereWithoutAgencyEmployeesInput = {
  where?: Prisma.AgenceWhereInput
  data: Prisma.XOR<Prisma.AgenceUpdateWithoutAgencyEmployeesInput, Prisma.AgenceUncheckedUpdateWithoutAgencyEmployeesInput>
}

export type AgenceUpdateWithoutAgencyEmployeesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUpdateManyWithoutAgenceNestedInput
  locataires?: Prisma.LocataireUpdateManyWithoutAgenceNestedInput
}

export type AgenceUncheckedUpdateWithoutAgencyEmployeesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUncheckedUpdateManyWithoutAgenceNestedInput
  locataires?: Prisma.LocataireUncheckedUpdateManyWithoutAgenceNestedInput
}

export type AgenceCreateWithoutLocatairesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceCreateNestedManyWithoutAgenceInput
  agencyEmployees?: Prisma.AgencyEmployeeCreateNestedManyWithoutAgencyInput
}

export type AgenceUncheckedCreateWithoutLocatairesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceUncheckedCreateNestedManyWithoutAgenceInput
  agencyEmployees?: Prisma.AgencyEmployeeUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgenceCreateOrConnectWithoutLocatairesInput = {
  where: Prisma.AgenceWhereUniqueInput
  create: Prisma.XOR<Prisma.AgenceCreateWithoutLocatairesInput, Prisma.AgenceUncheckedCreateWithoutLocatairesInput>
}

export type AgenceUpsertWithoutLocatairesInput = {
  update: Prisma.XOR<Prisma.AgenceUpdateWithoutLocatairesInput, Prisma.AgenceUncheckedUpdateWithoutLocatairesInput>
  create: Prisma.XOR<Prisma.AgenceCreateWithoutLocatairesInput, Prisma.AgenceUncheckedCreateWithoutLocatairesInput>
  where?: Prisma.AgenceWhereInput
}

export type AgenceUpdateToOneWithWhereWithoutLocatairesInput = {
  where?: Prisma.AgenceWhereInput
  data: Prisma.XOR<Prisma.AgenceUpdateWithoutLocatairesInput, Prisma.AgenceUncheckedUpdateWithoutLocatairesInput>
}

export type AgenceUpdateWithoutLocatairesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUpdateManyWithoutAgenceNestedInput
  agencyEmployees?: Prisma.AgencyEmployeeUpdateManyWithoutAgencyNestedInput
}

export type AgenceUncheckedUpdateWithoutLocatairesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUncheckedUpdateManyWithoutAgenceNestedInput
  agencyEmployees?: Prisma.AgencyEmployeeUncheckedUpdateManyWithoutAgencyNestedInput
}

export type AgenceCreateWithoutQuittancesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locataires?: Prisma.LocataireCreateNestedManyWithoutAgenceInput
  agencyEmployees?: Prisma.AgencyEmployeeCreateNestedManyWithoutAgencyInput
}

export type AgenceUncheckedCreateWithoutQuittancesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  locataires?: Prisma.LocataireUncheckedCreateNestedManyWithoutAgenceInput
  agencyEmployees?: Prisma.AgencyEmployeeUncheckedCreateNestedManyWithoutAgencyInput
}

export type AgenceCreateOrConnectWithoutQuittancesInput = {
  where: Prisma.AgenceWhereUniqueInput
  create: Prisma.XOR<Prisma.AgenceCreateWithoutQuittancesInput, Prisma.AgenceUncheckedCreateWithoutQuittancesInput>
}

export type AgenceUpsertWithoutQuittancesInput = {
  update: Prisma.XOR<Prisma.AgenceUpdateWithoutQuittancesInput, Prisma.AgenceUncheckedUpdateWithoutQuittancesInput>
  create: Prisma.XOR<Prisma.AgenceCreateWithoutQuittancesInput, Prisma.AgenceUncheckedCreateWithoutQuittancesInput>
  where?: Prisma.AgenceWhereInput
}

export type AgenceUpdateToOneWithWhereWithoutQuittancesInput = {
  where?: Prisma.AgenceWhereInput
  data: Prisma.XOR<Prisma.AgenceUpdateWithoutQuittancesInput, Prisma.AgenceUncheckedUpdateWithoutQuittancesInput>
}

export type AgenceUpdateWithoutQuittancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locataires?: Prisma.LocataireUpdateManyWithoutAgenceNestedInput
  agencyEmployees?: Prisma.AgencyEmployeeUpdateManyWithoutAgencyNestedInput
}

export type AgenceUncheckedUpdateWithoutQuittancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  locataires?: Prisma.LocataireUncheckedUpdateManyWithoutAgenceNestedInput
  agencyEmployees?: Prisma.AgencyEmployeeUncheckedUpdateManyWithoutAgencyNestedInput
}


/**
 * Count Type AgenceCountOutputType
 */

export type AgenceCountOutputType = {
  quittances: number
  locataires: number
  agencyEmployees: number
}

export type AgenceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quittances?: boolean | AgenceCountOutputTypeCountQuittancesArgs
  locataires?: boolean | AgenceCountOutputTypeCountLocatairesArgs
  agencyEmployees?: boolean | AgenceCountOutputTypeCountAgencyEmployeesArgs
}

/**
 * AgenceCountOutputType without action
 */
export type AgenceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgenceCountOutputType
   */
  select?: Prisma.AgenceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AgenceCountOutputType without action
 */
export type AgenceCountOutputTypeCountQuittancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuittanceWhereInput
}

/**
 * AgenceCountOutputType without action
 */
export type AgenceCountOutputTypeCountLocatairesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LocataireWhereInput
}

/**
 * AgenceCountOutputType without action
 */
export type AgenceCountOutputTypeCountAgencyEmployeesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencyEmployeeWhereInput
}


export type AgenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  adresse?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  quittances?: boolean | Prisma.Agence$quittancesArgs<ExtArgs>
  locataires?: boolean | Prisma.Agence$locatairesArgs<ExtArgs>
  agencyEmployees?: boolean | Prisma.Agence$agencyEmployeesArgs<ExtArgs>
  _count?: boolean | Prisma.AgenceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agence"]>



export type AgenceSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  adresse?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AgenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "adresse" | "role" | "createdAt" | "updatedAt", ExtArgs["result"]["agence"]>
export type AgenceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quittances?: boolean | Prisma.Agence$quittancesArgs<ExtArgs>
  locataires?: boolean | Prisma.Agence$locatairesArgs<ExtArgs>
  agencyEmployees?: boolean | Prisma.Agence$agencyEmployeesArgs<ExtArgs>
  _count?: boolean | Prisma.AgenceCountOutputTypeDefaultArgs<ExtArgs>
}

export type $AgencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Agence"
  objects: {
    quittances: Prisma.$QuittancePayload<ExtArgs>[]
    locataires: Prisma.$LocatairePayload<ExtArgs>[]
    agencyEmployees: Prisma.$AgencyEmployeePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    adresse: string
    role: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["agence"]>
  composites: {}
}

export type AgenceGetPayload<S extends boolean | null | undefined | AgenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgencePayload, S>

export type AgenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgenceCountAggregateInputType | true
  }

export interface AgenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Agence'], meta: { name: 'Agence' } }
  /**
   * Find zero or one Agence that matches the filter.
   * @param {AgenceFindUniqueArgs} args - Arguments to find a Agence
   * @example
   * // Get one Agence
   * const agence = await prisma.agence.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgenceFindUniqueArgs>(args: Prisma.SelectSubset<T, AgenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Agence that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgenceFindUniqueOrThrowArgs} args - Arguments to find a Agence
   * @example
   * // Get one Agence
   * const agence = await prisma.agence.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agence that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceFindFirstArgs} args - Arguments to find a Agence
   * @example
   * // Get one Agence
   * const agence = await prisma.agence.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgenceFindFirstArgs>(args?: Prisma.SelectSubset<T, AgenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agence that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceFindFirstOrThrowArgs} args - Arguments to find a Agence
   * @example
   * // Get one Agence
   * const agence = await prisma.agence.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Agences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Agences
   * const agences = await prisma.agence.findMany()
   * 
   * // Get first 10 Agences
   * const agences = await prisma.agence.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agenceWithIdOnly = await prisma.agence.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgenceFindManyArgs>(args?: Prisma.SelectSubset<T, AgenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Agence.
   * @param {AgenceCreateArgs} args - Arguments to create a Agence.
   * @example
   * // Create one Agence
   * const Agence = await prisma.agence.create({
   *   data: {
   *     // ... data to create a Agence
   *   }
   * })
   * 
   */
  create<T extends AgenceCreateArgs>(args: Prisma.SelectSubset<T, AgenceCreateArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Agences.
   * @param {AgenceCreateManyArgs} args - Arguments to create many Agences.
   * @example
   * // Create many Agences
   * const agence = await prisma.agence.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgenceCreateManyArgs>(args?: Prisma.SelectSubset<T, AgenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Agence.
   * @param {AgenceDeleteArgs} args - Arguments to delete one Agence.
   * @example
   * // Delete one Agence
   * const Agence = await prisma.agence.delete({
   *   where: {
   *     // ... filter to delete one Agence
   *   }
   * })
   * 
   */
  delete<T extends AgenceDeleteArgs>(args: Prisma.SelectSubset<T, AgenceDeleteArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Agence.
   * @param {AgenceUpdateArgs} args - Arguments to update one Agence.
   * @example
   * // Update one Agence
   * const agence = await prisma.agence.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgenceUpdateArgs>(args: Prisma.SelectSubset<T, AgenceUpdateArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Agences.
   * @param {AgenceDeleteManyArgs} args - Arguments to filter Agences to delete.
   * @example
   * // Delete a few Agences
   * const { count } = await prisma.agence.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Agences
   * const agence = await prisma.agence.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgenceUpdateManyArgs>(args: Prisma.SelectSubset<T, AgenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Agence.
   * @param {AgenceUpsertArgs} args - Arguments to update or create a Agence.
   * @example
   * // Update or create a Agence
   * const agence = await prisma.agence.upsert({
   *   create: {
   *     // ... data to create a Agence
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Agence we want to update
   *   }
   * })
   */
  upsert<T extends AgenceUpsertArgs>(args: Prisma.SelectSubset<T, AgenceUpsertArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Agences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceCountArgs} args - Arguments to filter Agences to count.
   * @example
   * // Count the number of Agences
   * const count = await prisma.agence.count({
   *   where: {
   *     // ... the filter for the Agences we want to count
   *   }
   * })
  **/
  count<T extends AgenceCountArgs>(
    args?: Prisma.Subset<T, AgenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Agence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgenceAggregateArgs>(args: Prisma.Subset<T, AgenceAggregateArgs>): Prisma.PrismaPromise<GetAgenceAggregateType<T>>

  /**
   * Group by Agence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgenceGroupByArgs['orderBy'] }
      : { orderBy?: AgenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Agence model
 */
readonly fields: AgenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Agence.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  quittances<T extends Prisma.Agence$quittancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Agence$quittancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuittancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  locataires<T extends Prisma.Agence$locatairesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Agence$locatairesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  agencyEmployees<T extends Prisma.Agence$agencyEmployeesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Agence$agencyEmployeesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Agence model
 */
export interface AgenceFieldRefs {
  readonly id: Prisma.FieldRef<"Agence", 'String'>
  readonly name: Prisma.FieldRef<"Agence", 'String'>
  readonly email: Prisma.FieldRef<"Agence", 'String'>
  readonly adresse: Prisma.FieldRef<"Agence", 'String'>
  readonly role: Prisma.FieldRef<"Agence", 'String'>
  readonly createdAt: Prisma.FieldRef<"Agence", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Agence", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Agence findUnique
 */
export type AgenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * Filter, which Agence to fetch.
   */
  where: Prisma.AgenceWhereUniqueInput
}

/**
 * Agence findUniqueOrThrow
 */
export type AgenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * Filter, which Agence to fetch.
   */
  where: Prisma.AgenceWhereUniqueInput
}

/**
 * Agence findFirst
 */
export type AgenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * Filter, which Agence to fetch.
   */
  where?: Prisma.AgenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agences to fetch.
   */
  orderBy?: Prisma.AgenceOrderByWithRelationInput | Prisma.AgenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agences.
   */
  cursor?: Prisma.AgenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agences.
   */
  distinct?: Prisma.AgenceScalarFieldEnum | Prisma.AgenceScalarFieldEnum[]
}

/**
 * Agence findFirstOrThrow
 */
export type AgenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * Filter, which Agence to fetch.
   */
  where?: Prisma.AgenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agences to fetch.
   */
  orderBy?: Prisma.AgenceOrderByWithRelationInput | Prisma.AgenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agences.
   */
  cursor?: Prisma.AgenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agences.
   */
  distinct?: Prisma.AgenceScalarFieldEnum | Prisma.AgenceScalarFieldEnum[]
}

/**
 * Agence findMany
 */
export type AgenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * Filter, which Agences to fetch.
   */
  where?: Prisma.AgenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agences to fetch.
   */
  orderBy?: Prisma.AgenceOrderByWithRelationInput | Prisma.AgenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Agences.
   */
  cursor?: Prisma.AgenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agences.
   */
  skip?: number
  distinct?: Prisma.AgenceScalarFieldEnum | Prisma.AgenceScalarFieldEnum[]
}

/**
 * Agence create
 */
export type AgenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * The data needed to create a Agence.
   */
  data: Prisma.XOR<Prisma.AgenceCreateInput, Prisma.AgenceUncheckedCreateInput>
}

/**
 * Agence createMany
 */
export type AgenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Agences.
   */
  data: Prisma.AgenceCreateManyInput | Prisma.AgenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Agence update
 */
export type AgenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * The data needed to update a Agence.
   */
  data: Prisma.XOR<Prisma.AgenceUpdateInput, Prisma.AgenceUncheckedUpdateInput>
  /**
   * Choose, which Agence to update.
   */
  where: Prisma.AgenceWhereUniqueInput
}

/**
 * Agence updateMany
 */
export type AgenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Agences.
   */
  data: Prisma.XOR<Prisma.AgenceUpdateManyMutationInput, Prisma.AgenceUncheckedUpdateManyInput>
  /**
   * Filter which Agences to update
   */
  where?: Prisma.AgenceWhereInput
  /**
   * Limit how many Agences to update.
   */
  limit?: number
}

/**
 * Agence upsert
 */
export type AgenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * The filter to search for the Agence to update in case it exists.
   */
  where: Prisma.AgenceWhereUniqueInput
  /**
   * In case the Agence found by the `where` argument doesn't exist, create a new Agence with this data.
   */
  create: Prisma.XOR<Prisma.AgenceCreateInput, Prisma.AgenceUncheckedCreateInput>
  /**
   * In case the Agence was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgenceUpdateInput, Prisma.AgenceUncheckedUpdateInput>
}

/**
 * Agence delete
 */
export type AgenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  /**
   * Filter which Agence to delete.
   */
  where: Prisma.AgenceWhereUniqueInput
}

/**
 * Agence deleteMany
 */
export type AgenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agences to delete
   */
  where?: Prisma.AgenceWhereInput
  /**
   * Limit how many Agences to delete.
   */
  limit?: number
}

/**
 * Agence.quittances
 */
export type Agence$quittancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quittance
   */
  select?: Prisma.QuittanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quittance
   */
  omit?: Prisma.QuittanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuittanceInclude<ExtArgs> | null
  where?: Prisma.QuittanceWhereInput
  orderBy?: Prisma.QuittanceOrderByWithRelationInput | Prisma.QuittanceOrderByWithRelationInput[]
  cursor?: Prisma.QuittanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuittanceScalarFieldEnum | Prisma.QuittanceScalarFieldEnum[]
}

/**
 * Agence.locataires
 */
export type Agence$locatairesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  where?: Prisma.LocataireWhereInput
  orderBy?: Prisma.LocataireOrderByWithRelationInput | Prisma.LocataireOrderByWithRelationInput[]
  cursor?: Prisma.LocataireWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LocataireScalarFieldEnum | Prisma.LocataireScalarFieldEnum[]
}

/**
 * Agence.agencyEmployees
 */
export type Agence$agencyEmployeesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  where?: Prisma.AgencyEmployeeWhereInput
  orderBy?: Prisma.AgencyEmployeeOrderByWithRelationInput | Prisma.AgencyEmployeeOrderByWithRelationInput[]
  cursor?: Prisma.AgencyEmployeeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgencyEmployeeScalarFieldEnum | Prisma.AgencyEmployeeScalarFieldEnum[]
}

/**
 * Agence without action
 */
export type AgenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
}
