
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgencyEmployee` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AgencyEmployee
 * 
 */
export type AgencyEmployeeModel = runtime.Types.Result.DefaultSelection<Prisma.$AgencyEmployeePayload>

export type AggregateAgencyEmployee = {
  _count: AgencyEmployeeCountAggregateOutputType | null
  _avg: AgencyEmployeeAvgAggregateOutputType | null
  _sum: AgencyEmployeeSumAggregateOutputType | null
  _min: AgencyEmployeeMinAggregateOutputType | null
  _max: AgencyEmployeeMaxAggregateOutputType | null
}

export type AgencyEmployeeAvgAggregateOutputType = {
  salary: runtime.Decimal | null
}

export type AgencyEmployeeSumAggregateOutputType = {
  salary: runtime.Decimal | null
}

export type AgencyEmployeeMinAggregateOutputType = {
  id: string | null
  userId: string | null
  agencyId: string | null
  position: string | null
  department: string | null
  hireDate: Date | null
  salary: runtime.Decimal | null
  isManager: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgencyEmployeeMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  agencyId: string | null
  position: string | null
  department: string | null
  hireDate: Date | null
  salary: runtime.Decimal | null
  isManager: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgencyEmployeeCountAggregateOutputType = {
  id: number
  userId: number
  agencyId: number
  position: number
  department: number
  hireDate: number
  salary: number
  isManager: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AgencyEmployeeAvgAggregateInputType = {
  salary?: true
}

export type AgencyEmployeeSumAggregateInputType = {
  salary?: true
}

export type AgencyEmployeeMinAggregateInputType = {
  id?: true
  userId?: true
  agencyId?: true
  position?: true
  department?: true
  hireDate?: true
  salary?: true
  isManager?: true
  createdAt?: true
  updatedAt?: true
}

export type AgencyEmployeeMaxAggregateInputType = {
  id?: true
  userId?: true
  agencyId?: true
  position?: true
  department?: true
  hireDate?: true
  salary?: true
  isManager?: true
  createdAt?: true
  updatedAt?: true
}

export type AgencyEmployeeCountAggregateInputType = {
  id?: true
  userId?: true
  agencyId?: true
  position?: true
  department?: true
  hireDate?: true
  salary?: true
  isManager?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AgencyEmployeeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgencyEmployee to aggregate.
   */
  where?: Prisma.AgencyEmployeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyEmployees to fetch.
   */
  orderBy?: Prisma.AgencyEmployeeOrderByWithRelationInput | Prisma.AgencyEmployeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgencyEmployeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyEmployees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyEmployees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgencyEmployees
  **/
  _count?: true | AgencyEmployeeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgencyEmployeeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgencyEmployeeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgencyEmployeeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgencyEmployeeMaxAggregateInputType
}

export type GetAgencyEmployeeAggregateType<T extends AgencyEmployeeAggregateArgs> = {
      [P in keyof T & keyof AggregateAgencyEmployee]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgencyEmployee[P]>
    : Prisma.GetScalarType<T[P], AggregateAgencyEmployee[P]>
}




export type AgencyEmployeeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgencyEmployeeWhereInput
  orderBy?: Prisma.AgencyEmployeeOrderByWithAggregationInput | Prisma.AgencyEmployeeOrderByWithAggregationInput[]
  by: Prisma.AgencyEmployeeScalarFieldEnum[] | Prisma.AgencyEmployeeScalarFieldEnum
  having?: Prisma.AgencyEmployeeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgencyEmployeeCountAggregateInputType | true
  _avg?: AgencyEmployeeAvgAggregateInputType
  _sum?: AgencyEmployeeSumAggregateInputType
  _min?: AgencyEmployeeMinAggregateInputType
  _max?: AgencyEmployeeMaxAggregateInputType
}

export type AgencyEmployeeGroupByOutputType = {
  id: string
  userId: string
  agencyId: string
  position: string
  department: string | null
  hireDate: Date
  salary: runtime.Decimal | null
  isManager: boolean
  createdAt: Date
  updatedAt: Date
  _count: AgencyEmployeeCountAggregateOutputType | null
  _avg: AgencyEmployeeAvgAggregateOutputType | null
  _sum: AgencyEmployeeSumAggregateOutputType | null
  _min: AgencyEmployeeMinAggregateOutputType | null
  _max: AgencyEmployeeMaxAggregateOutputType | null
}

type GetAgencyEmployeeGroupByPayload<T extends AgencyEmployeeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgencyEmployeeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgencyEmployeeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgencyEmployeeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgencyEmployeeGroupByOutputType[P]>
      }
    >
  >



export type AgencyEmployeeWhereInput = {
  AND?: Prisma.AgencyEmployeeWhereInput | Prisma.AgencyEmployeeWhereInput[]
  OR?: Prisma.AgencyEmployeeWhereInput[]
  NOT?: Prisma.AgencyEmployeeWhereInput | Prisma.AgencyEmployeeWhereInput[]
  id?: Prisma.StringFilter<"AgencyEmployee"> | string
  userId?: Prisma.StringFilter<"AgencyEmployee"> | string
  agencyId?: Prisma.StringFilter<"AgencyEmployee"> | string
  position?: Prisma.StringFilter<"AgencyEmployee"> | string
  department?: Prisma.StringNullableFilter<"AgencyEmployee"> | string | null
  hireDate?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  salary?: Prisma.DecimalNullableFilter<"AgencyEmployee"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFilter<"AgencyEmployee"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  agency?: Prisma.XOR<Prisma.AgenceScalarRelationFilter, Prisma.AgenceWhereInput>
}

export type AgencyEmployeeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  department?: Prisma.SortOrderInput | Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  salary?: Prisma.SortOrderInput | Prisma.SortOrder
  isManager?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  agency?: Prisma.AgenceOrderByWithRelationInput
  _relevance?: Prisma.AgencyEmployeeOrderByRelevanceInput
}

export type AgencyEmployeeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.AgencyEmployeeWhereInput | Prisma.AgencyEmployeeWhereInput[]
  OR?: Prisma.AgencyEmployeeWhereInput[]
  NOT?: Prisma.AgencyEmployeeWhereInput | Prisma.AgencyEmployeeWhereInput[]
  agencyId?: Prisma.StringFilter<"AgencyEmployee"> | string
  position?: Prisma.StringFilter<"AgencyEmployee"> | string
  department?: Prisma.StringNullableFilter<"AgencyEmployee"> | string | null
  hireDate?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  salary?: Prisma.DecimalNullableFilter<"AgencyEmployee"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFilter<"AgencyEmployee"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  agency?: Prisma.XOR<Prisma.AgenceScalarRelationFilter, Prisma.AgenceWhereInput>
}, "id" | "userId">

export type AgencyEmployeeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  department?: Prisma.SortOrderInput | Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  salary?: Prisma.SortOrderInput | Prisma.SortOrder
  isManager?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AgencyEmployeeCountOrderByAggregateInput
  _avg?: Prisma.AgencyEmployeeAvgOrderByAggregateInput
  _max?: Prisma.AgencyEmployeeMaxOrderByAggregateInput
  _min?: Prisma.AgencyEmployeeMinOrderByAggregateInput
  _sum?: Prisma.AgencyEmployeeSumOrderByAggregateInput
}

export type AgencyEmployeeScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgencyEmployeeScalarWhereWithAggregatesInput | Prisma.AgencyEmployeeScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgencyEmployeeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgencyEmployeeScalarWhereWithAggregatesInput | Prisma.AgencyEmployeeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgencyEmployee"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AgencyEmployee"> | string
  agencyId?: Prisma.StringWithAggregatesFilter<"AgencyEmployee"> | string
  position?: Prisma.StringWithAggregatesFilter<"AgencyEmployee"> | string
  department?: Prisma.StringNullableWithAggregatesFilter<"AgencyEmployee"> | string | null
  hireDate?: Prisma.DateTimeWithAggregatesFilter<"AgencyEmployee"> | Date | string
  salary?: Prisma.DecimalNullableWithAggregatesFilter<"AgencyEmployee"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolWithAggregatesFilter<"AgencyEmployee"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgencyEmployee"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AgencyEmployee"> | Date | string
}

export type AgencyEmployeeCreateInput = {
  id?: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAgencyEmployeeInput
  agency: Prisma.AgenceCreateNestedOneWithoutAgencyEmployeesInput
}

export type AgencyEmployeeUncheckedCreateInput = {
  id?: string
  userId: string
  agencyId: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyEmployeeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAgencyEmployeeNestedInput
  agency?: Prisma.AgenceUpdateOneRequiredWithoutAgencyEmployeesNestedInput
}

export type AgencyEmployeeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyEmployeeCreateManyInput = {
  id?: string
  userId: string
  agencyId: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyEmployeeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyEmployeeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyEmployeeListRelationFilter = {
  every?: Prisma.AgencyEmployeeWhereInput
  some?: Prisma.AgencyEmployeeWhereInput
  none?: Prisma.AgencyEmployeeWhereInput
}

export type AgencyEmployeeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgencyEmployeeOrderByRelevanceInput = {
  fields: Prisma.AgencyEmployeeOrderByRelevanceFieldEnum | Prisma.AgencyEmployeeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AgencyEmployeeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  department?: Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  isManager?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyEmployeeAvgOrderByAggregateInput = {
  salary?: Prisma.SortOrder
}

export type AgencyEmployeeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  department?: Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  isManager?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyEmployeeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  agencyId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  department?: Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  isManager?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgencyEmployeeSumOrderByAggregateInput = {
  salary?: Prisma.SortOrder
}

export type AgencyEmployeeNullableScalarRelationFilter = {
  is?: Prisma.AgencyEmployeeWhereInput | null
  isNot?: Prisma.AgencyEmployeeWhereInput | null
}

export type AgencyEmployeeCreateNestedManyWithoutAgencyInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput> | Prisma.AgencyEmployeeCreateWithoutAgencyInput[] | Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput | Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput[]
  createMany?: Prisma.AgencyEmployeeCreateManyAgencyInputEnvelope
  connect?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
}

export type AgencyEmployeeUncheckedCreateNestedManyWithoutAgencyInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput> | Prisma.AgencyEmployeeCreateWithoutAgencyInput[] | Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput | Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput[]
  createMany?: Prisma.AgencyEmployeeCreateManyAgencyInputEnvelope
  connect?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
}

export type AgencyEmployeeUpdateManyWithoutAgencyNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput> | Prisma.AgencyEmployeeCreateWithoutAgencyInput[] | Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput | Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput[]
  upsert?: Prisma.AgencyEmployeeUpsertWithWhereUniqueWithoutAgencyInput | Prisma.AgencyEmployeeUpsertWithWhereUniqueWithoutAgencyInput[]
  createMany?: Prisma.AgencyEmployeeCreateManyAgencyInputEnvelope
  set?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  disconnect?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  delete?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  connect?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  update?: Prisma.AgencyEmployeeUpdateWithWhereUniqueWithoutAgencyInput | Prisma.AgencyEmployeeUpdateWithWhereUniqueWithoutAgencyInput[]
  updateMany?: Prisma.AgencyEmployeeUpdateManyWithWhereWithoutAgencyInput | Prisma.AgencyEmployeeUpdateManyWithWhereWithoutAgencyInput[]
  deleteMany?: Prisma.AgencyEmployeeScalarWhereInput | Prisma.AgencyEmployeeScalarWhereInput[]
}

export type AgencyEmployeeUncheckedUpdateManyWithoutAgencyNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput> | Prisma.AgencyEmployeeCreateWithoutAgencyInput[] | Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput[]
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput | Prisma.AgencyEmployeeCreateOrConnectWithoutAgencyInput[]
  upsert?: Prisma.AgencyEmployeeUpsertWithWhereUniqueWithoutAgencyInput | Prisma.AgencyEmployeeUpsertWithWhereUniqueWithoutAgencyInput[]
  createMany?: Prisma.AgencyEmployeeCreateManyAgencyInputEnvelope
  set?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  disconnect?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  delete?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  connect?: Prisma.AgencyEmployeeWhereUniqueInput | Prisma.AgencyEmployeeWhereUniqueInput[]
  update?: Prisma.AgencyEmployeeUpdateWithWhereUniqueWithoutAgencyInput | Prisma.AgencyEmployeeUpdateWithWhereUniqueWithoutAgencyInput[]
  updateMany?: Prisma.AgencyEmployeeUpdateManyWithWhereWithoutAgencyInput | Prisma.AgencyEmployeeUpdateManyWithWhereWithoutAgencyInput[]
  deleteMany?: Prisma.AgencyEmployeeScalarWhereInput | Prisma.AgencyEmployeeScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type AgencyEmployeeCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutUserInput, Prisma.AgencyEmployeeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutUserInput
  connect?: Prisma.AgencyEmployeeWhereUniqueInput
}

export type AgencyEmployeeUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutUserInput, Prisma.AgencyEmployeeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutUserInput
  connect?: Prisma.AgencyEmployeeWhereUniqueInput
}

export type AgencyEmployeeUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutUserInput, Prisma.AgencyEmployeeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutUserInput
  upsert?: Prisma.AgencyEmployeeUpsertWithoutUserInput
  disconnect?: Prisma.AgencyEmployeeWhereInput | boolean
  delete?: Prisma.AgencyEmployeeWhereInput | boolean
  connect?: Prisma.AgencyEmployeeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyEmployeeUpdateToOneWithWhereWithoutUserInput, Prisma.AgencyEmployeeUpdateWithoutUserInput>, Prisma.AgencyEmployeeUncheckedUpdateWithoutUserInput>
}

export type AgencyEmployeeUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutUserInput, Prisma.AgencyEmployeeUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AgencyEmployeeCreateOrConnectWithoutUserInput
  upsert?: Prisma.AgencyEmployeeUpsertWithoutUserInput
  disconnect?: Prisma.AgencyEmployeeWhereInput | boolean
  delete?: Prisma.AgencyEmployeeWhereInput | boolean
  connect?: Prisma.AgencyEmployeeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgencyEmployeeUpdateToOneWithWhereWithoutUserInput, Prisma.AgencyEmployeeUpdateWithoutUserInput>, Prisma.AgencyEmployeeUncheckedUpdateWithoutUserInput>
}

export type AgencyEmployeeCreateWithoutAgencyInput = {
  id?: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAgencyEmployeeInput
}

export type AgencyEmployeeUncheckedCreateWithoutAgencyInput = {
  id?: string
  userId: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyEmployeeCreateOrConnectWithoutAgencyInput = {
  where: Prisma.AgencyEmployeeWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput>
}

export type AgencyEmployeeCreateManyAgencyInputEnvelope = {
  data: Prisma.AgencyEmployeeCreateManyAgencyInput | Prisma.AgencyEmployeeCreateManyAgencyInput[]
  skipDuplicates?: boolean
}

export type AgencyEmployeeUpsertWithWhereUniqueWithoutAgencyInput = {
  where: Prisma.AgencyEmployeeWhereUniqueInput
  update: Prisma.XOR<Prisma.AgencyEmployeeUpdateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedUpdateWithoutAgencyInput>
  create: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedCreateWithoutAgencyInput>
}

export type AgencyEmployeeUpdateWithWhereUniqueWithoutAgencyInput = {
  where: Prisma.AgencyEmployeeWhereUniqueInput
  data: Prisma.XOR<Prisma.AgencyEmployeeUpdateWithoutAgencyInput, Prisma.AgencyEmployeeUncheckedUpdateWithoutAgencyInput>
}

export type AgencyEmployeeUpdateManyWithWhereWithoutAgencyInput = {
  where: Prisma.AgencyEmployeeScalarWhereInput
  data: Prisma.XOR<Prisma.AgencyEmployeeUpdateManyMutationInput, Prisma.AgencyEmployeeUncheckedUpdateManyWithoutAgencyInput>
}

export type AgencyEmployeeScalarWhereInput = {
  AND?: Prisma.AgencyEmployeeScalarWhereInput | Prisma.AgencyEmployeeScalarWhereInput[]
  OR?: Prisma.AgencyEmployeeScalarWhereInput[]
  NOT?: Prisma.AgencyEmployeeScalarWhereInput | Prisma.AgencyEmployeeScalarWhereInput[]
  id?: Prisma.StringFilter<"AgencyEmployee"> | string
  userId?: Prisma.StringFilter<"AgencyEmployee"> | string
  agencyId?: Prisma.StringFilter<"AgencyEmployee"> | string
  position?: Prisma.StringFilter<"AgencyEmployee"> | string
  department?: Prisma.StringNullableFilter<"AgencyEmployee"> | string | null
  hireDate?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  salary?: Prisma.DecimalNullableFilter<"AgencyEmployee"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFilter<"AgencyEmployee"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgencyEmployee"> | Date | string
}

export type AgencyEmployeeCreateWithoutUserInput = {
  id?: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  agency: Prisma.AgenceCreateNestedOneWithoutAgencyEmployeesInput
}

export type AgencyEmployeeUncheckedCreateWithoutUserInput = {
  id?: string
  agencyId: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyEmployeeCreateOrConnectWithoutUserInput = {
  where: Prisma.AgencyEmployeeWhereUniqueInput
  create: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutUserInput, Prisma.AgencyEmployeeUncheckedCreateWithoutUserInput>
}

export type AgencyEmployeeUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.AgencyEmployeeUpdateWithoutUserInput, Prisma.AgencyEmployeeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AgencyEmployeeCreateWithoutUserInput, Prisma.AgencyEmployeeUncheckedCreateWithoutUserInput>
  where?: Prisma.AgencyEmployeeWhereInput
}

export type AgencyEmployeeUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.AgencyEmployeeWhereInput
  data: Prisma.XOR<Prisma.AgencyEmployeeUpdateWithoutUserInput, Prisma.AgencyEmployeeUncheckedUpdateWithoutUserInput>
}

export type AgencyEmployeeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agency?: Prisma.AgenceUpdateOneRequiredWithoutAgencyEmployeesNestedInput
}

export type AgencyEmployeeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agencyId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyEmployeeCreateManyAgencyInput = {
  id?: string
  userId: string
  position: string
  department?: string | null
  hireDate: Date | string
  salary?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgencyEmployeeUpdateWithoutAgencyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAgencyEmployeeNestedInput
}

export type AgencyEmployeeUncheckedUpdateWithoutAgencyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgencyEmployeeUncheckedUpdateManyWithoutAgencyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salary?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  isManager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AgencyEmployeeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  agencyId?: boolean
  position?: boolean
  department?: boolean
  hireDate?: boolean
  salary?: boolean
  isManager?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  agency?: boolean | Prisma.AgenceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agencyEmployee"]>



export type AgencyEmployeeSelectScalar = {
  id?: boolean
  userId?: boolean
  agencyId?: boolean
  position?: boolean
  department?: boolean
  hireDate?: boolean
  salary?: boolean
  isManager?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AgencyEmployeeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "agencyId" | "position" | "department" | "hireDate" | "salary" | "isManager" | "createdAt" | "updatedAt", ExtArgs["result"]["agencyEmployee"]>
export type AgencyEmployeeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  agency?: boolean | Prisma.AgenceDefaultArgs<ExtArgs>
}

export type $AgencyEmployeePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgencyEmployee"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    agency: Prisma.$AgencePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    agencyId: string
    position: string
    department: string | null
    hireDate: Date
    salary: runtime.Decimal | null
    isManager: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["agencyEmployee"]>
  composites: {}
}

export type AgencyEmployeeGetPayload<S extends boolean | null | undefined | AgencyEmployeeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload, S>

export type AgencyEmployeeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgencyEmployeeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgencyEmployeeCountAggregateInputType | true
  }

export interface AgencyEmployeeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgencyEmployee'], meta: { name: 'AgencyEmployee' } }
  /**
   * Find zero or one AgencyEmployee that matches the filter.
   * @param {AgencyEmployeeFindUniqueArgs} args - Arguments to find a AgencyEmployee
   * @example
   * // Get one AgencyEmployee
   * const agencyEmployee = await prisma.agencyEmployee.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgencyEmployeeFindUniqueArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgencyEmployee that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgencyEmployeeFindUniqueOrThrowArgs} args - Arguments to find a AgencyEmployee
   * @example
   * // Get one AgencyEmployee
   * const agencyEmployee = await prisma.agencyEmployee.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgencyEmployeeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgencyEmployee that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeFindFirstArgs} args - Arguments to find a AgencyEmployee
   * @example
   * // Get one AgencyEmployee
   * const agencyEmployee = await prisma.agencyEmployee.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgencyEmployeeFindFirstArgs>(args?: Prisma.SelectSubset<T, AgencyEmployeeFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgencyEmployee that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeFindFirstOrThrowArgs} args - Arguments to find a AgencyEmployee
   * @example
   * // Get one AgencyEmployee
   * const agencyEmployee = await prisma.agencyEmployee.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgencyEmployeeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgencyEmployeeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgencyEmployees that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgencyEmployees
   * const agencyEmployees = await prisma.agencyEmployee.findMany()
   * 
   * // Get first 10 AgencyEmployees
   * const agencyEmployees = await prisma.agencyEmployee.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agencyEmployeeWithIdOnly = await prisma.agencyEmployee.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgencyEmployeeFindManyArgs>(args?: Prisma.SelectSubset<T, AgencyEmployeeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgencyEmployee.
   * @param {AgencyEmployeeCreateArgs} args - Arguments to create a AgencyEmployee.
   * @example
   * // Create one AgencyEmployee
   * const AgencyEmployee = await prisma.agencyEmployee.create({
   *   data: {
   *     // ... data to create a AgencyEmployee
   *   }
   * })
   * 
   */
  create<T extends AgencyEmployeeCreateArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeCreateArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgencyEmployees.
   * @param {AgencyEmployeeCreateManyArgs} args - Arguments to create many AgencyEmployees.
   * @example
   * // Create many AgencyEmployees
   * const agencyEmployee = await prisma.agencyEmployee.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgencyEmployeeCreateManyArgs>(args?: Prisma.SelectSubset<T, AgencyEmployeeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a AgencyEmployee.
   * @param {AgencyEmployeeDeleteArgs} args - Arguments to delete one AgencyEmployee.
   * @example
   * // Delete one AgencyEmployee
   * const AgencyEmployee = await prisma.agencyEmployee.delete({
   *   where: {
   *     // ... filter to delete one AgencyEmployee
   *   }
   * })
   * 
   */
  delete<T extends AgencyEmployeeDeleteArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeDeleteArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgencyEmployee.
   * @param {AgencyEmployeeUpdateArgs} args - Arguments to update one AgencyEmployee.
   * @example
   * // Update one AgencyEmployee
   * const agencyEmployee = await prisma.agencyEmployee.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgencyEmployeeUpdateArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeUpdateArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgencyEmployees.
   * @param {AgencyEmployeeDeleteManyArgs} args - Arguments to filter AgencyEmployees to delete.
   * @example
   * // Delete a few AgencyEmployees
   * const { count } = await prisma.agencyEmployee.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgencyEmployeeDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgencyEmployeeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgencyEmployees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgencyEmployees
   * const agencyEmployee = await prisma.agencyEmployee.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgencyEmployeeUpdateManyArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one AgencyEmployee.
   * @param {AgencyEmployeeUpsertArgs} args - Arguments to update or create a AgencyEmployee.
   * @example
   * // Update or create a AgencyEmployee
   * const agencyEmployee = await prisma.agencyEmployee.upsert({
   *   create: {
   *     // ... data to create a AgencyEmployee
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgencyEmployee we want to update
   *   }
   * })
   */
  upsert<T extends AgencyEmployeeUpsertArgs>(args: Prisma.SelectSubset<T, AgencyEmployeeUpsertArgs<ExtArgs>>): Prisma.Prisma__AgencyEmployeeClient<runtime.Types.Result.GetResult<Prisma.$AgencyEmployeePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgencyEmployees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeCountArgs} args - Arguments to filter AgencyEmployees to count.
   * @example
   * // Count the number of AgencyEmployees
   * const count = await prisma.agencyEmployee.count({
   *   where: {
   *     // ... the filter for the AgencyEmployees we want to count
   *   }
   * })
  **/
  count<T extends AgencyEmployeeCountArgs>(
    args?: Prisma.Subset<T, AgencyEmployeeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgencyEmployeeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgencyEmployee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgencyEmployeeAggregateArgs>(args: Prisma.Subset<T, AgencyEmployeeAggregateArgs>): Prisma.PrismaPromise<GetAgencyEmployeeAggregateType<T>>

  /**
   * Group by AgencyEmployee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgencyEmployeeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgencyEmployeeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgencyEmployeeGroupByArgs['orderBy'] }
      : { orderBy?: AgencyEmployeeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgencyEmployeeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgencyEmployeeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgencyEmployee model
 */
readonly fields: AgencyEmployeeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgencyEmployee.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgencyEmployeeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  agency<T extends Prisma.AgenceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgenceDefaultArgs<ExtArgs>>): Prisma.Prisma__AgenceClient<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgencyEmployee model
 */
export interface AgencyEmployeeFieldRefs {
  readonly id: Prisma.FieldRef<"AgencyEmployee", 'String'>
  readonly userId: Prisma.FieldRef<"AgencyEmployee", 'String'>
  readonly agencyId: Prisma.FieldRef<"AgencyEmployee", 'String'>
  readonly position: Prisma.FieldRef<"AgencyEmployee", 'String'>
  readonly department: Prisma.FieldRef<"AgencyEmployee", 'String'>
  readonly hireDate: Prisma.FieldRef<"AgencyEmployee", 'DateTime'>
  readonly salary: Prisma.FieldRef<"AgencyEmployee", 'Decimal'>
  readonly isManager: Prisma.FieldRef<"AgencyEmployee", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AgencyEmployee", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AgencyEmployee", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgencyEmployee findUnique
 */
export type AgencyEmployeeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * Filter, which AgencyEmployee to fetch.
   */
  where: Prisma.AgencyEmployeeWhereUniqueInput
}

/**
 * AgencyEmployee findUniqueOrThrow
 */
export type AgencyEmployeeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * Filter, which AgencyEmployee to fetch.
   */
  where: Prisma.AgencyEmployeeWhereUniqueInput
}

/**
 * AgencyEmployee findFirst
 */
export type AgencyEmployeeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * Filter, which AgencyEmployee to fetch.
   */
  where?: Prisma.AgencyEmployeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyEmployees to fetch.
   */
  orderBy?: Prisma.AgencyEmployeeOrderByWithRelationInput | Prisma.AgencyEmployeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgencyEmployees.
   */
  cursor?: Prisma.AgencyEmployeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyEmployees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyEmployees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencyEmployees.
   */
  distinct?: Prisma.AgencyEmployeeScalarFieldEnum | Prisma.AgencyEmployeeScalarFieldEnum[]
}

/**
 * AgencyEmployee findFirstOrThrow
 */
export type AgencyEmployeeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * Filter, which AgencyEmployee to fetch.
   */
  where?: Prisma.AgencyEmployeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyEmployees to fetch.
   */
  orderBy?: Prisma.AgencyEmployeeOrderByWithRelationInput | Prisma.AgencyEmployeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgencyEmployees.
   */
  cursor?: Prisma.AgencyEmployeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyEmployees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyEmployees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgencyEmployees.
   */
  distinct?: Prisma.AgencyEmployeeScalarFieldEnum | Prisma.AgencyEmployeeScalarFieldEnum[]
}

/**
 * AgencyEmployee findMany
 */
export type AgencyEmployeeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * Filter, which AgencyEmployees to fetch.
   */
  where?: Prisma.AgencyEmployeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgencyEmployees to fetch.
   */
  orderBy?: Prisma.AgencyEmployeeOrderByWithRelationInput | Prisma.AgencyEmployeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgencyEmployees.
   */
  cursor?: Prisma.AgencyEmployeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgencyEmployees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgencyEmployees.
   */
  skip?: number
  distinct?: Prisma.AgencyEmployeeScalarFieldEnum | Prisma.AgencyEmployeeScalarFieldEnum[]
}

/**
 * AgencyEmployee create
 */
export type AgencyEmployeeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * The data needed to create a AgencyEmployee.
   */
  data: Prisma.XOR<Prisma.AgencyEmployeeCreateInput, Prisma.AgencyEmployeeUncheckedCreateInput>
}

/**
 * AgencyEmployee createMany
 */
export type AgencyEmployeeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgencyEmployees.
   */
  data: Prisma.AgencyEmployeeCreateManyInput | Prisma.AgencyEmployeeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AgencyEmployee update
 */
export type AgencyEmployeeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * The data needed to update a AgencyEmployee.
   */
  data: Prisma.XOR<Prisma.AgencyEmployeeUpdateInput, Prisma.AgencyEmployeeUncheckedUpdateInput>
  /**
   * Choose, which AgencyEmployee to update.
   */
  where: Prisma.AgencyEmployeeWhereUniqueInput
}

/**
 * AgencyEmployee updateMany
 */
export type AgencyEmployeeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgencyEmployees.
   */
  data: Prisma.XOR<Prisma.AgencyEmployeeUpdateManyMutationInput, Prisma.AgencyEmployeeUncheckedUpdateManyInput>
  /**
   * Filter which AgencyEmployees to update
   */
  where?: Prisma.AgencyEmployeeWhereInput
  /**
   * Limit how many AgencyEmployees to update.
   */
  limit?: number
}

/**
 * AgencyEmployee upsert
 */
export type AgencyEmployeeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * The filter to search for the AgencyEmployee to update in case it exists.
   */
  where: Prisma.AgencyEmployeeWhereUniqueInput
  /**
   * In case the AgencyEmployee found by the `where` argument doesn't exist, create a new AgencyEmployee with this data.
   */
  create: Prisma.XOR<Prisma.AgencyEmployeeCreateInput, Prisma.AgencyEmployeeUncheckedCreateInput>
  /**
   * In case the AgencyEmployee was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgencyEmployeeUpdateInput, Prisma.AgencyEmployeeUncheckedUpdateInput>
}

/**
 * AgencyEmployee delete
 */
export type AgencyEmployeeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
  /**
   * Filter which AgencyEmployee to delete.
   */
  where: Prisma.AgencyEmployeeWhereUniqueInput
}

/**
 * AgencyEmployee deleteMany
 */
export type AgencyEmployeeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgencyEmployees to delete
   */
  where?: Prisma.AgencyEmployeeWhereInput
  /**
   * Limit how many AgencyEmployees to delete.
   */
  limit?: number
}

/**
 * AgencyEmployee without action
 */
export type AgencyEmployeeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgencyEmployee
   */
  select?: Prisma.AgencyEmployeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgencyEmployee
   */
  omit?: Prisma.AgencyEmployeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgencyEmployeeInclude<ExtArgs> | null
}
