
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Locataire` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Locataire
 * 
 */
export type LocataireModel = runtime.Types.Result.DefaultSelection<Prisma.$LocatairePayload>

export type AggregateLocataire = {
  _count: LocataireCountAggregateOutputType | null
  _min: LocataireMinAggregateOutputType | null
  _max: LocataireMaxAggregateOutputType | null
}

export type LocataireMinAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  email: string | null
  adresse: string | null
  role: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LocataireMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  email: string | null
  adresse: string | null
  role: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LocataireCountAggregateOutputType = {
  id: number
  userId: number
  name: number
  email: number
  adresse: number
  role: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LocataireMinAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  email?: true
  adresse?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type LocataireMaxAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  email?: true
  adresse?: true
  role?: true
  createdAt?: true
  updatedAt?: true
}

export type LocataireCountAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  email?: true
  adresse?: true
  role?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LocataireAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Locataire to aggregate.
   */
  where?: Prisma.LocataireWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Locataires to fetch.
   */
  orderBy?: Prisma.LocataireOrderByWithRelationInput | Prisma.LocataireOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LocataireWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Locataires from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Locataires.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Locataires
  **/
  _count?: true | LocataireCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LocataireMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LocataireMaxAggregateInputType
}

export type GetLocataireAggregateType<T extends LocataireAggregateArgs> = {
      [P in keyof T & keyof AggregateLocataire]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLocataire[P]>
    : Prisma.GetScalarType<T[P], AggregateLocataire[P]>
}




export type LocataireGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LocataireWhereInput
  orderBy?: Prisma.LocataireOrderByWithAggregationInput | Prisma.LocataireOrderByWithAggregationInput[]
  by: Prisma.LocataireScalarFieldEnum[] | Prisma.LocataireScalarFieldEnum
  having?: Prisma.LocataireScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LocataireCountAggregateInputType | true
  _min?: LocataireMinAggregateInputType
  _max?: LocataireMaxAggregateInputType
}

export type LocataireGroupByOutputType = {
  id: string
  userId: string
  name: string
  email: string
  adresse: string
  role: string
  createdAt: Date
  updatedAt: Date
  _count: LocataireCountAggregateOutputType | null
  _min: LocataireMinAggregateOutputType | null
  _max: LocataireMaxAggregateOutputType | null
}

type GetLocataireGroupByPayload<T extends LocataireGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LocataireGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LocataireGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LocataireGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LocataireGroupByOutputType[P]>
      }
    >
  >



export type LocataireWhereInput = {
  AND?: Prisma.LocataireWhereInput | Prisma.LocataireWhereInput[]
  OR?: Prisma.LocataireWhereInput[]
  NOT?: Prisma.LocataireWhereInput | Prisma.LocataireWhereInput[]
  id?: Prisma.StringFilter<"Locataire"> | string
  userId?: Prisma.StringFilter<"Locataire"> | string
  name?: Prisma.StringFilter<"Locataire"> | string
  email?: Prisma.StringFilter<"Locataire"> | string
  adresse?: Prisma.StringFilter<"Locataire"> | string
  role?: Prisma.StringFilter<"Locataire"> | string
  createdAt?: Prisma.DateTimeFilter<"Locataire"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Locataire"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  quittances?: Prisma.QuittanceListRelationFilter
  agences?: Prisma.AgenceListRelationFilter
}

export type LocataireOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  quittances?: Prisma.QuittanceOrderByRelationAggregateInput
  agences?: Prisma.AgenceOrderByRelationAggregateInput
  _relevance?: Prisma.LocataireOrderByRelevanceInput
}

export type LocataireWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  email?: string
  AND?: Prisma.LocataireWhereInput | Prisma.LocataireWhereInput[]
  OR?: Prisma.LocataireWhereInput[]
  NOT?: Prisma.LocataireWhereInput | Prisma.LocataireWhereInput[]
  name?: Prisma.StringFilter<"Locataire"> | string
  adresse?: Prisma.StringFilter<"Locataire"> | string
  role?: Prisma.StringFilter<"Locataire"> | string
  createdAt?: Prisma.DateTimeFilter<"Locataire"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Locataire"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  quittances?: Prisma.QuittanceListRelationFilter
  agences?: Prisma.AgenceListRelationFilter
}, "id" | "userId" | "email">

export type LocataireOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LocataireCountOrderByAggregateInput
  _max?: Prisma.LocataireMaxOrderByAggregateInput
  _min?: Prisma.LocataireMinOrderByAggregateInput
}

export type LocataireScalarWhereWithAggregatesInput = {
  AND?: Prisma.LocataireScalarWhereWithAggregatesInput | Prisma.LocataireScalarWhereWithAggregatesInput[]
  OR?: Prisma.LocataireScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LocataireScalarWhereWithAggregatesInput | Prisma.LocataireScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Locataire"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Locataire"> | string
  name?: Prisma.StringWithAggregatesFilter<"Locataire"> | string
  email?: Prisma.StringWithAggregatesFilter<"Locataire"> | string
  adresse?: Prisma.StringWithAggregatesFilter<"Locataire"> | string
  role?: Prisma.StringWithAggregatesFilter<"Locataire"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Locataire"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Locataire"> | Date | string
}

export type LocataireCreateInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLocataireInput
  quittances?: Prisma.QuittanceCreateNestedManyWithoutLocataireInput
  agences?: Prisma.AgenceCreateNestedManyWithoutLocatairesInput
}

export type LocataireUncheckedCreateInput = {
  id?: string
  userId: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceUncheckedCreateNestedManyWithoutLocataireInput
  agences?: Prisma.AgenceUncheckedCreateNestedManyWithoutLocatairesInput
}

export type LocataireUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLocataireNestedInput
  quittances?: Prisma.QuittanceUpdateManyWithoutLocataireNestedInput
  agences?: Prisma.AgenceUpdateManyWithoutLocatairesNestedInput
}

export type LocataireUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUncheckedUpdateManyWithoutLocataireNestedInput
  agences?: Prisma.AgenceUncheckedUpdateManyWithoutLocatairesNestedInput
}

export type LocataireCreateManyInput = {
  id?: string
  userId: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LocataireUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LocataireUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LocataireListRelationFilter = {
  every?: Prisma.LocataireWhereInput
  some?: Prisma.LocataireWhereInput
  none?: Prisma.LocataireWhereInput
}

export type LocataireOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LocataireOrderByRelevanceInput = {
  fields: Prisma.LocataireOrderByRelevanceFieldEnum | Prisma.LocataireOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type LocataireCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocataireMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocataireMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  adresse?: Prisma.SortOrder
  role?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LocataireScalarRelationFilter = {
  is?: Prisma.LocataireWhereInput
  isNot?: Prisma.LocataireWhereInput
}

export type LocataireNullableScalarRelationFilter = {
  is?: Prisma.LocataireWhereInput | null
  isNot?: Prisma.LocataireWhereInput | null
}

export type LocataireCreateNestedManyWithoutAgencesInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutAgencesInput, Prisma.LocataireUncheckedCreateWithoutAgencesInput> | Prisma.LocataireCreateWithoutAgencesInput[] | Prisma.LocataireUncheckedCreateWithoutAgencesInput[]
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutAgencesInput | Prisma.LocataireCreateOrConnectWithoutAgencesInput[]
  connect?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
}

export type LocataireUncheckedCreateNestedManyWithoutAgencesInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutAgencesInput, Prisma.LocataireUncheckedCreateWithoutAgencesInput> | Prisma.LocataireCreateWithoutAgencesInput[] | Prisma.LocataireUncheckedCreateWithoutAgencesInput[]
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutAgencesInput | Prisma.LocataireCreateOrConnectWithoutAgencesInput[]
  connect?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
}

export type LocataireUpdateManyWithoutAgencesNestedInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutAgencesInput, Prisma.LocataireUncheckedCreateWithoutAgencesInput> | Prisma.LocataireCreateWithoutAgencesInput[] | Prisma.LocataireUncheckedCreateWithoutAgencesInput[]
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutAgencesInput | Prisma.LocataireCreateOrConnectWithoutAgencesInput[]
  upsert?: Prisma.LocataireUpsertWithWhereUniqueWithoutAgencesInput | Prisma.LocataireUpsertWithWhereUniqueWithoutAgencesInput[]
  set?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  disconnect?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  delete?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  connect?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  update?: Prisma.LocataireUpdateWithWhereUniqueWithoutAgencesInput | Prisma.LocataireUpdateWithWhereUniqueWithoutAgencesInput[]
  updateMany?: Prisma.LocataireUpdateManyWithWhereWithoutAgencesInput | Prisma.LocataireUpdateManyWithWhereWithoutAgencesInput[]
  deleteMany?: Prisma.LocataireScalarWhereInput | Prisma.LocataireScalarWhereInput[]
}

export type LocataireUncheckedUpdateManyWithoutAgencesNestedInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutAgencesInput, Prisma.LocataireUncheckedCreateWithoutAgencesInput> | Prisma.LocataireCreateWithoutAgencesInput[] | Prisma.LocataireUncheckedCreateWithoutAgencesInput[]
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutAgencesInput | Prisma.LocataireCreateOrConnectWithoutAgencesInput[]
  upsert?: Prisma.LocataireUpsertWithWhereUniqueWithoutAgencesInput | Prisma.LocataireUpsertWithWhereUniqueWithoutAgencesInput[]
  set?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  disconnect?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  delete?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  connect?: Prisma.LocataireWhereUniqueInput | Prisma.LocataireWhereUniqueInput[]
  update?: Prisma.LocataireUpdateWithWhereUniqueWithoutAgencesInput | Prisma.LocataireUpdateWithWhereUniqueWithoutAgencesInput[]
  updateMany?: Prisma.LocataireUpdateManyWithWhereWithoutAgencesInput | Prisma.LocataireUpdateManyWithWhereWithoutAgencesInput[]
  deleteMany?: Prisma.LocataireScalarWhereInput | Prisma.LocataireScalarWhereInput[]
}

export type LocataireCreateNestedOneWithoutQuittancesInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutQuittancesInput, Prisma.LocataireUncheckedCreateWithoutQuittancesInput>
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutQuittancesInput
  connect?: Prisma.LocataireWhereUniqueInput
}

export type LocataireUpdateOneRequiredWithoutQuittancesNestedInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutQuittancesInput, Prisma.LocataireUncheckedCreateWithoutQuittancesInput>
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutQuittancesInput
  upsert?: Prisma.LocataireUpsertWithoutQuittancesInput
  connect?: Prisma.LocataireWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LocataireUpdateToOneWithWhereWithoutQuittancesInput, Prisma.LocataireUpdateWithoutQuittancesInput>, Prisma.LocataireUncheckedUpdateWithoutQuittancesInput>
}

export type LocataireCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutUserInput, Prisma.LocataireUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutUserInput
  connect?: Prisma.LocataireWhereUniqueInput
}

export type LocataireUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutUserInput, Prisma.LocataireUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutUserInput
  connect?: Prisma.LocataireWhereUniqueInput
}

export type LocataireUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutUserInput, Prisma.LocataireUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutUserInput
  upsert?: Prisma.LocataireUpsertWithoutUserInput
  disconnect?: Prisma.LocataireWhereInput | boolean
  delete?: Prisma.LocataireWhereInput | boolean
  connect?: Prisma.LocataireWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LocataireUpdateToOneWithWhereWithoutUserInput, Prisma.LocataireUpdateWithoutUserInput>, Prisma.LocataireUncheckedUpdateWithoutUserInput>
}

export type LocataireUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LocataireCreateWithoutUserInput, Prisma.LocataireUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.LocataireCreateOrConnectWithoutUserInput
  upsert?: Prisma.LocataireUpsertWithoutUserInput
  disconnect?: Prisma.LocataireWhereInput | boolean
  delete?: Prisma.LocataireWhereInput | boolean
  connect?: Prisma.LocataireWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LocataireUpdateToOneWithWhereWithoutUserInput, Prisma.LocataireUpdateWithoutUserInput>, Prisma.LocataireUncheckedUpdateWithoutUserInput>
}

export type LocataireCreateWithoutAgencesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLocataireInput
  quittances?: Prisma.QuittanceCreateNestedManyWithoutLocataireInput
}

export type LocataireUncheckedCreateWithoutAgencesInput = {
  id?: string
  userId: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceUncheckedCreateNestedManyWithoutLocataireInput
}

export type LocataireCreateOrConnectWithoutAgencesInput = {
  where: Prisma.LocataireWhereUniqueInput
  create: Prisma.XOR<Prisma.LocataireCreateWithoutAgencesInput, Prisma.LocataireUncheckedCreateWithoutAgencesInput>
}

export type LocataireUpsertWithWhereUniqueWithoutAgencesInput = {
  where: Prisma.LocataireWhereUniqueInput
  update: Prisma.XOR<Prisma.LocataireUpdateWithoutAgencesInput, Prisma.LocataireUncheckedUpdateWithoutAgencesInput>
  create: Prisma.XOR<Prisma.LocataireCreateWithoutAgencesInput, Prisma.LocataireUncheckedCreateWithoutAgencesInput>
}

export type LocataireUpdateWithWhereUniqueWithoutAgencesInput = {
  where: Prisma.LocataireWhereUniqueInput
  data: Prisma.XOR<Prisma.LocataireUpdateWithoutAgencesInput, Prisma.LocataireUncheckedUpdateWithoutAgencesInput>
}

export type LocataireUpdateManyWithWhereWithoutAgencesInput = {
  where: Prisma.LocataireScalarWhereInput
  data: Prisma.XOR<Prisma.LocataireUpdateManyMutationInput, Prisma.LocataireUncheckedUpdateManyWithoutAgencesInput>
}

export type LocataireScalarWhereInput = {
  AND?: Prisma.LocataireScalarWhereInput | Prisma.LocataireScalarWhereInput[]
  OR?: Prisma.LocataireScalarWhereInput[]
  NOT?: Prisma.LocataireScalarWhereInput | Prisma.LocataireScalarWhereInput[]
  id?: Prisma.StringFilter<"Locataire"> | string
  userId?: Prisma.StringFilter<"Locataire"> | string
  name?: Prisma.StringFilter<"Locataire"> | string
  email?: Prisma.StringFilter<"Locataire"> | string
  adresse?: Prisma.StringFilter<"Locataire"> | string
  role?: Prisma.StringFilter<"Locataire"> | string
  createdAt?: Prisma.DateTimeFilter<"Locataire"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Locataire"> | Date | string
}

export type LocataireCreateWithoutQuittancesInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLocataireInput
  agences?: Prisma.AgenceCreateNestedManyWithoutLocatairesInput
}

export type LocataireUncheckedCreateWithoutQuittancesInput = {
  id?: string
  userId: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  agences?: Prisma.AgenceUncheckedCreateNestedManyWithoutLocatairesInput
}

export type LocataireCreateOrConnectWithoutQuittancesInput = {
  where: Prisma.LocataireWhereUniqueInput
  create: Prisma.XOR<Prisma.LocataireCreateWithoutQuittancesInput, Prisma.LocataireUncheckedCreateWithoutQuittancesInput>
}

export type LocataireUpsertWithoutQuittancesInput = {
  update: Prisma.XOR<Prisma.LocataireUpdateWithoutQuittancesInput, Prisma.LocataireUncheckedUpdateWithoutQuittancesInput>
  create: Prisma.XOR<Prisma.LocataireCreateWithoutQuittancesInput, Prisma.LocataireUncheckedCreateWithoutQuittancesInput>
  where?: Prisma.LocataireWhereInput
}

export type LocataireUpdateToOneWithWhereWithoutQuittancesInput = {
  where?: Prisma.LocataireWhereInput
  data: Prisma.XOR<Prisma.LocataireUpdateWithoutQuittancesInput, Prisma.LocataireUncheckedUpdateWithoutQuittancesInput>
}

export type LocataireUpdateWithoutQuittancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLocataireNestedInput
  agences?: Prisma.AgenceUpdateManyWithoutLocatairesNestedInput
}

export type LocataireUncheckedUpdateWithoutQuittancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agences?: Prisma.AgenceUncheckedUpdateManyWithoutLocatairesNestedInput
}

export type LocataireCreateWithoutUserInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceCreateNestedManyWithoutLocataireInput
  agences?: Prisma.AgenceCreateNestedManyWithoutLocatairesInput
}

export type LocataireUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  email: string
  adresse: string
  role?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  quittances?: Prisma.QuittanceUncheckedCreateNestedManyWithoutLocataireInput
  agences?: Prisma.AgenceUncheckedCreateNestedManyWithoutLocatairesInput
}

export type LocataireCreateOrConnectWithoutUserInput = {
  where: Prisma.LocataireWhereUniqueInput
  create: Prisma.XOR<Prisma.LocataireCreateWithoutUserInput, Prisma.LocataireUncheckedCreateWithoutUserInput>
}

export type LocataireUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.LocataireUpdateWithoutUserInput, Prisma.LocataireUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LocataireCreateWithoutUserInput, Prisma.LocataireUncheckedCreateWithoutUserInput>
  where?: Prisma.LocataireWhereInput
}

export type LocataireUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.LocataireWhereInput
  data: Prisma.XOR<Prisma.LocataireUpdateWithoutUserInput, Prisma.LocataireUncheckedUpdateWithoutUserInput>
}

export type LocataireUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUpdateManyWithoutLocataireNestedInput
  agences?: Prisma.AgenceUpdateManyWithoutLocatairesNestedInput
}

export type LocataireUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUncheckedUpdateManyWithoutLocataireNestedInput
  agences?: Prisma.AgenceUncheckedUpdateManyWithoutLocatairesNestedInput
}

export type LocataireUpdateWithoutAgencesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLocataireNestedInput
  quittances?: Prisma.QuittanceUpdateManyWithoutLocataireNestedInput
}

export type LocataireUncheckedUpdateWithoutAgencesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quittances?: Prisma.QuittanceUncheckedUpdateManyWithoutLocataireNestedInput
}

export type LocataireUncheckedUpdateManyWithoutAgencesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  adresse?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type LocataireCountOutputType
 */

export type LocataireCountOutputType = {
  quittances: number
  agences: number
}

export type LocataireCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quittances?: boolean | LocataireCountOutputTypeCountQuittancesArgs
  agences?: boolean | LocataireCountOutputTypeCountAgencesArgs
}

/**
 * LocataireCountOutputType without action
 */
export type LocataireCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LocataireCountOutputType
   */
  select?: Prisma.LocataireCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LocataireCountOutputType without action
 */
export type LocataireCountOutputTypeCountQuittancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuittanceWhereInput
}

/**
 * LocataireCountOutputType without action
 */
export type LocataireCountOutputTypeCountAgencesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgenceWhereInput
}


export type LocataireSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  email?: boolean
  adresse?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quittances?: boolean | Prisma.Locataire$quittancesArgs<ExtArgs>
  agences?: boolean | Prisma.Locataire$agencesArgs<ExtArgs>
  _count?: boolean | Prisma.LocataireCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["locataire"]>



export type LocataireSelectScalar = {
  id?: boolean
  userId?: boolean
  name?: boolean
  email?: boolean
  adresse?: boolean
  role?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LocataireOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "name" | "email" | "adresse" | "role" | "createdAt" | "updatedAt", ExtArgs["result"]["locataire"]>
export type LocataireInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quittances?: boolean | Prisma.Locataire$quittancesArgs<ExtArgs>
  agences?: boolean | Prisma.Locataire$agencesArgs<ExtArgs>
  _count?: boolean | Prisma.LocataireCountOutputTypeDefaultArgs<ExtArgs>
}

export type $LocatairePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Locataire"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    quittances: Prisma.$QuittancePayload<ExtArgs>[]
    agences: Prisma.$AgencePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    name: string
    email: string
    adresse: string
    role: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["locataire"]>
  composites: {}
}

export type LocataireGetPayload<S extends boolean | null | undefined | LocataireDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LocatairePayload, S>

export type LocataireCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LocataireFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LocataireCountAggregateInputType | true
  }

export interface LocataireDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Locataire'], meta: { name: 'Locataire' } }
  /**
   * Find zero or one Locataire that matches the filter.
   * @param {LocataireFindUniqueArgs} args - Arguments to find a Locataire
   * @example
   * // Get one Locataire
   * const locataire = await prisma.locataire.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LocataireFindUniqueArgs>(args: Prisma.SelectSubset<T, LocataireFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Locataire that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LocataireFindUniqueOrThrowArgs} args - Arguments to find a Locataire
   * @example
   * // Get one Locataire
   * const locataire = await prisma.locataire.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LocataireFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LocataireFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Locataire that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireFindFirstArgs} args - Arguments to find a Locataire
   * @example
   * // Get one Locataire
   * const locataire = await prisma.locataire.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LocataireFindFirstArgs>(args?: Prisma.SelectSubset<T, LocataireFindFirstArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Locataire that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireFindFirstOrThrowArgs} args - Arguments to find a Locataire
   * @example
   * // Get one Locataire
   * const locataire = await prisma.locataire.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LocataireFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LocataireFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Locataires that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Locataires
   * const locataires = await prisma.locataire.findMany()
   * 
   * // Get first 10 Locataires
   * const locataires = await prisma.locataire.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const locataireWithIdOnly = await prisma.locataire.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LocataireFindManyArgs>(args?: Prisma.SelectSubset<T, LocataireFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Locataire.
   * @param {LocataireCreateArgs} args - Arguments to create a Locataire.
   * @example
   * // Create one Locataire
   * const Locataire = await prisma.locataire.create({
   *   data: {
   *     // ... data to create a Locataire
   *   }
   * })
   * 
   */
  create<T extends LocataireCreateArgs>(args: Prisma.SelectSubset<T, LocataireCreateArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Locataires.
   * @param {LocataireCreateManyArgs} args - Arguments to create many Locataires.
   * @example
   * // Create many Locataires
   * const locataire = await prisma.locataire.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LocataireCreateManyArgs>(args?: Prisma.SelectSubset<T, LocataireCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Locataire.
   * @param {LocataireDeleteArgs} args - Arguments to delete one Locataire.
   * @example
   * // Delete one Locataire
   * const Locataire = await prisma.locataire.delete({
   *   where: {
   *     // ... filter to delete one Locataire
   *   }
   * })
   * 
   */
  delete<T extends LocataireDeleteArgs>(args: Prisma.SelectSubset<T, LocataireDeleteArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Locataire.
   * @param {LocataireUpdateArgs} args - Arguments to update one Locataire.
   * @example
   * // Update one Locataire
   * const locataire = await prisma.locataire.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LocataireUpdateArgs>(args: Prisma.SelectSubset<T, LocataireUpdateArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Locataires.
   * @param {LocataireDeleteManyArgs} args - Arguments to filter Locataires to delete.
   * @example
   * // Delete a few Locataires
   * const { count } = await prisma.locataire.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LocataireDeleteManyArgs>(args?: Prisma.SelectSubset<T, LocataireDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Locataires.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Locataires
   * const locataire = await prisma.locataire.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LocataireUpdateManyArgs>(args: Prisma.SelectSubset<T, LocataireUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Locataire.
   * @param {LocataireUpsertArgs} args - Arguments to update or create a Locataire.
   * @example
   * // Update or create a Locataire
   * const locataire = await prisma.locataire.upsert({
   *   create: {
   *     // ... data to create a Locataire
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Locataire we want to update
   *   }
   * })
   */
  upsert<T extends LocataireUpsertArgs>(args: Prisma.SelectSubset<T, LocataireUpsertArgs<ExtArgs>>): Prisma.Prisma__LocataireClient<runtime.Types.Result.GetResult<Prisma.$LocatairePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Locataires.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireCountArgs} args - Arguments to filter Locataires to count.
   * @example
   * // Count the number of Locataires
   * const count = await prisma.locataire.count({
   *   where: {
   *     // ... the filter for the Locataires we want to count
   *   }
   * })
  **/
  count<T extends LocataireCountArgs>(
    args?: Prisma.Subset<T, LocataireCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LocataireCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Locataire.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LocataireAggregateArgs>(args: Prisma.Subset<T, LocataireAggregateArgs>): Prisma.PrismaPromise<GetLocataireAggregateType<T>>

  /**
   * Group by Locataire.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LocataireGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LocataireGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LocataireGroupByArgs['orderBy'] }
      : { orderBy?: LocataireGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LocataireGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLocataireGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Locataire model
 */
readonly fields: LocataireFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Locataire.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LocataireClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  quittances<T extends Prisma.Locataire$quittancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Locataire$quittancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuittancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  agences<T extends Prisma.Locataire$agencesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Locataire$agencesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Locataire model
 */
export interface LocataireFieldRefs {
  readonly id: Prisma.FieldRef<"Locataire", 'String'>
  readonly userId: Prisma.FieldRef<"Locataire", 'String'>
  readonly name: Prisma.FieldRef<"Locataire", 'String'>
  readonly email: Prisma.FieldRef<"Locataire", 'String'>
  readonly adresse: Prisma.FieldRef<"Locataire", 'String'>
  readonly role: Prisma.FieldRef<"Locataire", 'String'>
  readonly createdAt: Prisma.FieldRef<"Locataire", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Locataire", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Locataire findUnique
 */
export type LocataireFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * Filter, which Locataire to fetch.
   */
  where: Prisma.LocataireWhereUniqueInput
}

/**
 * Locataire findUniqueOrThrow
 */
export type LocataireFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * Filter, which Locataire to fetch.
   */
  where: Prisma.LocataireWhereUniqueInput
}

/**
 * Locataire findFirst
 */
export type LocataireFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * Filter, which Locataire to fetch.
   */
  where?: Prisma.LocataireWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Locataires to fetch.
   */
  orderBy?: Prisma.LocataireOrderByWithRelationInput | Prisma.LocataireOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Locataires.
   */
  cursor?: Prisma.LocataireWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Locataires from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Locataires.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Locataires.
   */
  distinct?: Prisma.LocataireScalarFieldEnum | Prisma.LocataireScalarFieldEnum[]
}

/**
 * Locataire findFirstOrThrow
 */
export type LocataireFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * Filter, which Locataire to fetch.
   */
  where?: Prisma.LocataireWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Locataires to fetch.
   */
  orderBy?: Prisma.LocataireOrderByWithRelationInput | Prisma.LocataireOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Locataires.
   */
  cursor?: Prisma.LocataireWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Locataires from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Locataires.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Locataires.
   */
  distinct?: Prisma.LocataireScalarFieldEnum | Prisma.LocataireScalarFieldEnum[]
}

/**
 * Locataire findMany
 */
export type LocataireFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * Filter, which Locataires to fetch.
   */
  where?: Prisma.LocataireWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Locataires to fetch.
   */
  orderBy?: Prisma.LocataireOrderByWithRelationInput | Prisma.LocataireOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Locataires.
   */
  cursor?: Prisma.LocataireWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Locataires from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Locataires.
   */
  skip?: number
  distinct?: Prisma.LocataireScalarFieldEnum | Prisma.LocataireScalarFieldEnum[]
}

/**
 * Locataire create
 */
export type LocataireCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * The data needed to create a Locataire.
   */
  data: Prisma.XOR<Prisma.LocataireCreateInput, Prisma.LocataireUncheckedCreateInput>
}

/**
 * Locataire createMany
 */
export type LocataireCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Locataires.
   */
  data: Prisma.LocataireCreateManyInput | Prisma.LocataireCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Locataire update
 */
export type LocataireUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * The data needed to update a Locataire.
   */
  data: Prisma.XOR<Prisma.LocataireUpdateInput, Prisma.LocataireUncheckedUpdateInput>
  /**
   * Choose, which Locataire to update.
   */
  where: Prisma.LocataireWhereUniqueInput
}

/**
 * Locataire updateMany
 */
export type LocataireUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Locataires.
   */
  data: Prisma.XOR<Prisma.LocataireUpdateManyMutationInput, Prisma.LocataireUncheckedUpdateManyInput>
  /**
   * Filter which Locataires to update
   */
  where?: Prisma.LocataireWhereInput
  /**
   * Limit how many Locataires to update.
   */
  limit?: number
}

/**
 * Locataire upsert
 */
export type LocataireUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * The filter to search for the Locataire to update in case it exists.
   */
  where: Prisma.LocataireWhereUniqueInput
  /**
   * In case the Locataire found by the `where` argument doesn't exist, create a new Locataire with this data.
   */
  create: Prisma.XOR<Prisma.LocataireCreateInput, Prisma.LocataireUncheckedCreateInput>
  /**
   * In case the Locataire was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LocataireUpdateInput, Prisma.LocataireUncheckedUpdateInput>
}

/**
 * Locataire delete
 */
export type LocataireDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
  /**
   * Filter which Locataire to delete.
   */
  where: Prisma.LocataireWhereUniqueInput
}

/**
 * Locataire deleteMany
 */
export type LocataireDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Locataires to delete
   */
  where?: Prisma.LocataireWhereInput
  /**
   * Limit how many Locataires to delete.
   */
  limit?: number
}

/**
 * Locataire.quittances
 */
export type Locataire$quittancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quittance
   */
  select?: Prisma.QuittanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quittance
   */
  omit?: Prisma.QuittanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuittanceInclude<ExtArgs> | null
  where?: Prisma.QuittanceWhereInput
  orderBy?: Prisma.QuittanceOrderByWithRelationInput | Prisma.QuittanceOrderByWithRelationInput[]
  cursor?: Prisma.QuittanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuittanceScalarFieldEnum | Prisma.QuittanceScalarFieldEnum[]
}

/**
 * Locataire.agences
 */
export type Locataire$agencesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agence
   */
  select?: Prisma.AgenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agence
   */
  omit?: Prisma.AgenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgenceInclude<ExtArgs> | null
  where?: Prisma.AgenceWhereInput
  orderBy?: Prisma.AgenceOrderByWithRelationInput | Prisma.AgenceOrderByWithRelationInput[]
  cursor?: Prisma.AgenceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgenceScalarFieldEnum | Prisma.AgenceScalarFieldEnum[]
}

/**
 * Locataire without action
 */
export type LocataireDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locataire
   */
  select?: Prisma.LocataireSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locataire
   */
  omit?: Prisma.LocataireOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LocataireInclude<ExtArgs> | null
}
