
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Agence.js'
export type * from './models/AgencyEmployee.js'
export type * from './models/Locataire.js'
export type * from './models/Quittance.js'
export type * from './models/User.js'
export type * from './commonInputTypes.js'